- platform: moon
- platform: yr
  monitored_conditions:
    - symbol

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
#    - 2
#    - 3
#    - 4
#    - 5
  scan_interval:
    minutes: 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
#above is used for lovelace animated card. below is the delta that i use for my own state card
    - dew_point
    - cloud_cover
    - minutely_summary
    - hourly_summary
    - temperature_high
    - temperature_low
#- platform: fitbit
#  monitored_resources:
#    - "body/weight"
#    - "body/fat"
#    - "activities/steps"
#    - "activities/floors"
#    - "activities/calories"
- platform: nest
  monitored_conditions:
  - 'co_status'
  - 'smoke_status'
  - 'battery_level'
  

- platform: template
  sensors:
    garage_status:
      friendly_name: 'Door Status'
      value_template: '{% if states.cover.garage_door %}
          {% if states.cover.garage_door.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.garage_door.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.garage_door.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.garage_door.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Offline
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
      icon_template: '{% if states.cover.garage_door %}
          {% if states.cover.garage_door.attributes["door_state"] == "open" %}
            mdi:garage-open
          {% elif states.cover.garage_door.attributes["door_state"] == "closed" %}
            mdi:garage
          {% elif states.cover.garage_door.attributes["door_state"] == "opening" %}
            mdi:garage-open
          {% elif states.cover.garage_door.attributes["door_state"] == "closing" %}
            mdi:garage
          {% else %}
            mdi:help-network
          {% endif %}
          {% else %}
          mdi:help-network
          {% endif %}'
    garage_car_present:
      friendly_name: 'Is Car Present'
      value_template: '{% if states.cover.garage_door %}
          {% if states.cover.garage_door.state == "open" %}
            Unsure when door open
          {% elif ((states.cover.garage_door.attributes["distance_sensor"] > 90) and (states.cover.garage_door.attributes["distance_sensor"] < 210)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
      icon_template: '{% if states.cover.garage_door %}
          {% if states.cover.garage_door.state == "open" %}
            mdi:help-box
          {% elif ((states.cover.garage_door.attributes["distance_sensor"] > 90) and (states.cover.garage_door.attributes["distance_sensor"] < 210)) %}
            mdi:car
          {% else %}
            mdi:car
          {% endif %}
          {% else %}
            mdi:help-network
          {% endif %}'

- platform: template
  sensors:
    weather_icon:
      entity_id: sensor.dark_sky_icon
      value_template: >
        {% if states.sensor.dark_sky_precip_probability.state |int > 80 %}
          {% if states.sensor.dark_sky_precip.state == 'rain' %}
            rain
          {% elif states.sensor.dark_sky_precip.state == 'snow' %}
            snow
          {% endif %}
        {% elif states.sensor.dark_sky_cloud_coverage.state |int > 40 %}
          {% if states.sensor.dark_sky_cloud_coverage.state |int > 80 %}
            cloudy
          {% elif is_state('sun.sun', 'above_horizon') %}
            partly-cloudy-day
          {% else %}
            partly-cloudy-night
          {% endif %}
        {% elif is_state('sun.sun', 'above_horizon') %}
          clear-day
        {% else %}
          clear-night
        {% endif %}

- platform: rest
  resource: https://api.weather.gov/alerts/active/count
  name: NWS Alert Count
  value_template: >
    {% if value_json.zones.IAZ052 is defined %}
      {{ value_json.zones.IAZ052 }}
    {% elif value_json.zones.IAC113 is defined %}
      {{ value_json.zones.IAC113 }}
    {% else %}
      0
    {% endif %}
  headers:
    User-Agent: Homeassistant
    Accept: application/ld+json
  scan_interval: 60

- platform: rest
  resource: https://api.weather.gov/alerts/active?zone=IAZ052,IAC113
  name: NWS Alert Event
  value_template: >
    {% if value_json.features[0] is defined %}
      {{ value_json['features'][0]['properties'].event }}
    {% else %}
      None
    {% endif %}
  json_attributes:
    - features
  headers:
    User-Agent: Homeassistant
    Accept: application/geo+json
  scan_interval: 60
